WITH JOINED_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
MONTHLY_PURCHASED AS (
    SELECT
        YEAR(O.SALES_DATE) AS YEAR,
        MONTH(O.SALES_DATE) AS MONTH,
        COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS
    FROM ONLINE_SALE O JOIN JOINED_2021 J ON O.USER_ID = J.USER_ID
    GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
)
SELECT
    M.YEAR,
    M.MONTH,
    M.PURCHASED_USERS,
    ROUND(M.PURCHASED_USERS / (SELECT COUNT(*) FROM JOINED_2021), 1) AS PUCHASED_RATIO
FROM MONTHLY_PURCHASED M
ORDER BY M.YEAR, M.MONTH