WITH A AS (
    SELECT
        C.CAR_TYPE,
        C.DAILY_FEE,
        H.HISTORY_ID,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
        CASE
            WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 THEN '90일 이상'
            WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 30 THEN '30일 이상'
            WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 7 THEN '7일 이상'
        END DURATION_TYPE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        JOIN CAR_RENTAL_COMPANY_CAR C
        ON H.CAR_ID = C.CAR_ID
    WHERE CAR_TYPE = '트럭'
)

SELECT
    HISTORY_ID,
    ROUND(A.DAILY_FEE * A.DURATION * (100 - IFNULL(B.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM A
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
    ON A.CAR_TYPE = B.CAR_TYPE AND A.DURATION_TYPE = B.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC
