SELECT B.YEAR, ABS(A.SIZE_OF_COLONY - B.MAX_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A
JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
) B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY B.YEAR, YEAR_DEV

